import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import * as gari from "gari";
import styles from "../styles/Home.module.css";
import {
	InvokeMethodEventNames,
	TriggerInvokeMethodsEvent,
} from "../utils/invokeMethod.helper";

export default function Home() {
	const [clientId, setClientId] = useState("");

	const [token, setToken] = useState("");

	// const location = useLocation();
	const parsedToken = async () => {
		const search = window.location.search;

		const params = new URLSearchParams(search);
		const tokenparams = params.get("token");
		const clientId = params.get("clientId");

		setToken(tokenparams);
		setClientId(clientId);
	};

	useEffect(() => {
		parsedToken();
	}, []);

	console.log("token from outside..,", token);

	useEffect(() => {
		if (clientId) {
			gari.sdkInitialize(clientId, "hjhdjhgjhg");
		}
	}, [clientId]);

	const createOrGetWallet = async () => {
		console.log("wokring.....");
		try {
			if (token) {
				console.log("token ...", token);
				const resp = await gari.createWalletOrGetWallet(token);
				TriggerInvokeMethodsEvent(InvokeMethodEventNames.walletData, {
					data: resp,
				});
				console.log("response from create wallet ", resp);
			}
		} catch (err) {
			console.log(err);
		}
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<h4>Mobile SDK</h4>
			<button
				onClick={() => {
					createOrGetWallet();
				}}
			>
				create or get wallet
			</button>
		</div>
	);
}
